Add info on how to get a reference to a game plugin
FlaxEngine/FlaxDocs pull request #171
Opened 2024-12-20 15:07 UTC by xxSeys1

I anyone more experienced with C# notices a potential issue with the `Instance` property, please point them out. So far this has worked perfectly fine for me though.

This also is a pattern that's used throughout the Flax source code, so I think it's fine to suggest that here.

![image](https://github.com/user-attachments/assets/36dbc9da-032b-4ed5-b441-c241141b6553)

2025-01-06 20:48 UTC, mafiesto4 requested changes

2025-01-06 20:48 UTC, mafiesto4 commented on manual/scripting/plugins/index.md
> +    get
You could simplify this to `get => PluginManager.GetPlugin<MyPlugin>();`. Especially, because in Editor when playing the static variable might remaining the same but plugin gets loaded/unloaded/loaded between play sessions.

2025-01-13 11:05 UTC, xxSeys1 commented on manual/scripting/plugins/index.md
> +    get
Added in: https://github.com/FlaxEngine/FlaxDocs/pull/171/commits/f8b6d5a3aa0189c545bc6d8e51f05395451c8e60

Ty for review :)

2025-01-13 16:20 UTC, mafiesto4 approved these changes

2025-01-13 16:20 UTC, merged